name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Use built artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: List files
        run: |
          ls -la
          ls -la dist

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
